language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - python -m unittest tests/test_basic.py                                                                                                                 2.47      11:42    11.12.19
